using UnityEngine;
using UnityEditor;
using System.IO;

namespace GlimmerOfHope.Editor
{
    /// <summary>
    /// Custom Inspector for MeshScaleCalibrator: displays the current scale
    /// of the object and a button to freeze this scale into the mesh, generating
    /// (or overwriting) a calibrated Prefab in the project.
    /// </summary>
    [CustomEditor(typeof(MeshScaleCalibrator))]
    public class MeshScaleCalibratorEditor : UnityEditor.Editor
    {
        #region Private Fields
        // Folder where the calibrated Prefabs generated by this tool are stored.
        const string kCalibratedFolder = "Assets/_Project/Prefabs/CalibratedPrefabs";
        #endregion

        #region Unity LifeCycle
        public override void OnInspectorGUI()
        {
            var calibrator = (MeshScaleCalibrator)target;
            var go = calibrator.gameObject;
            var meshFilter = go.GetComponent<MeshFilter>();

            GUILayout.Space(6);
            EditorGUILayout.LabelField("Calibration d'échelle Blender → Unity", EditorStyles.boldLabel);

            if (meshFilter == null || meshFilter.sharedMesh == null)
            {
                EditorGUILayout.HelpBox(
                    "Aucun MeshFilter/Mesh valide sur cet objet, impossible de calibrer.",
                    MessageType.Warning);
                return;
            }

            Vector3 currentScale = go.transform.localScale;
            bool isNeutral = Vector3.Distance(currentScale, Vector3.one) < 0.0001f;

            EditorGUILayout.Vector3Field("Scale actuel (Transform)", currentScale);

            if (calibrator.IsCalibrated)
            {
                EditorGUILayout.HelpBox(
                    $"Cet objet a déjà été calibré.\nPrefab calibré : {calibrator.CalibratedPrefabPath}",
                    MessageType.Info);
            }

            GUILayout.Space(6);

            if (isNeutral)
            {
                EditorGUILayout.HelpBox(
                    "Le scale est déjà à 1/1/1 — rien à calibrer pour le moment. " +
                    "Ajustez le Transform dans la scène de test jusqu'à la bonne taille, " +
                    "puis revenez ici.",
                    MessageType.None);
                return;
            }

            EditorGUILayout.HelpBox(
                $"Cliquer ci-dessous va :\n" +
                $"1) Multiplier les vertices du mesh par {FormatScale(currentScale)}.\n" +
                $"2) Créer/écraser un Prefab calibré dans '{kCalibratedFolder}/'.\n" +
                $"3) Remettre le Transform de cet objet à 1/1/1.\n" +
                $"Toute future utilisation du Prefab calibré affichera Scale = 1/1/1.",
                MessageType.Warning);

            GUIStyle bigButton = new GUIStyle(GUI.skin.button) { fontSize = 13, fixedHeight = 34 };
            if (GUILayout.Button("💾 Sauvegarder la calibration", bigButton))
            {
                if (EditorUtility.DisplayDialog(
                    "Sauvegarder la calibration",
                    $"Confirmer : figer le scale {FormatScale(currentScale)} dans le mesh " +
                    $"et créer/écraser le Prefab calibré ?\nCette action est non destructive pour le FBX d'origine.",
                    "Confirmer", "Annuler"))
                {
                    SaveCalibration(calibrator, meshFilter, currentScale);
                }
            }
        }
        #endregion

        #region Private Methods
        static string FormatScale(Vector3 s) => $"({s.x:0.###}, {s.y:0.###}, {s.z:0.###})";

        void SaveCalibration(MeshScaleCalibrator calibrator, MeshFilter meshFilter, Vector3 scale)
        {
            GameObject go = calibrator.gameObject;
            Transform t = go.transform;
            Mesh sourceMesh = meshFilter.sharedMesh;

            Undo.RegisterCompleteObjectUndo(go, "Sauvegarder la calibration");
            Undo.RegisterCompleteObjectUndo(t, "Sauvegarder la calibration");

            // Bake the scale into a copy of the mesh 
            Mesh bakedMesh = Object.Instantiate(sourceMesh);
            bakedMesh.name = sourceMesh.name + "_Calibrated";

            Matrix4x4 matrix = Matrix4x4.Scale(scale);

            Vector3[] vertices = bakedMesh.vertices;
            for (int i = 0; i < vertices.Length; i++)
                vertices[i] = matrix.MultiplyPoint3x4(vertices[i]);
            bakedMesh.vertices = vertices;

            Vector3[] normals = bakedMesh.normals;
            if (normals != null && normals.Length == vertices.Length)
            {
                Matrix4x4 normalMatrix = matrix.inverse.transpose;
                for (int i = 0; i < normals.Length; i++)
                    normals[i] = normalMatrix.MultiplyVector(normals[i]).normalized;
                bakedMesh.normals = normals;
            }

            bakedMesh.RecalculateBounds();

            if (matrix.determinant < 0f)
                FlipTriangles(bakedMesh);

            // Save the calibrated mesh as an asset
            EnsureFolderExists(kCalibratedFolder + "/Meshs");
            string meshAssetPath = AssetDatabase.GenerateUniqueAssetPath(
                Path.Combine(kCalibratedFolder + "/Meshs", bakedMesh.name + ".asset"));
            AssetDatabase.CreateAsset(bakedMesh, meshAssetPath);

            // Apply the calibrated mesh and flatten the Transform 
            meshFilter.sharedMesh = bakedMesh;

            MeshCollider collider = go.GetComponent<MeshCollider>();
            if (collider != null && collider.sharedMesh == sourceMesh)
                collider.sharedMesh = bakedMesh;

            t.localScale = Vector3.one;

            // If the object is already a Prefab instance, we
            // unpack it before saving, to obtain a new unique and
            // independent Prefab (otherwise Unity would create a Prefab Variant
            // always linked to the uncalibrated source)
            if (PrefabUtility.IsPartOfPrefabInstance(go))
            {
                PrefabUtility.UnpackPrefabInstance(
                    go, PrefabUnpackMode.Completely, InteractionMode.AutomatedAction);
            }

            //Creation/overwriting of the calibrated Prefab 
            string prefabName = SanitizeFileName(go.name) + "_Calibrated.prefab";
            string prefabPath = calibrator.IsCalibrated
                ? calibrator.CalibratedPrefabPath
                : AssetDatabase.GenerateUniqueAssetPath(Path.Combine(kCalibratedFolder, prefabName));

            PrefabUtility.SaveAsPrefabAssetAndConnect(
                go, prefabPath, InteractionMode.AutomatedAction, out bool success);

            if (!success)
            {
                Debug.LogError($"[MeshScaleCalibrator] Échec de la sauvegarde du Prefab calibré pour '{go.name}'.");
                EditorUtility.DisplayDialog("Erreur", "La sauvegarde du Prefab calibré a échoué. Voir la Console.", "OK");
                return;
            }

            calibrator.SetCalibratedPrefabPath(prefabPath);
            EditorUtility.SetDirty(calibrator);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();

            Debug.Log($"[MeshScaleCalibrator] Calibration sauvegardée pour '{go.name}'. " +
                      $"Mesh calibré : {meshAssetPath} | Prefab calibré : {prefabPath}");

            EditorUtility.DisplayDialog(
                "Calibration sauvegardée",
                $"Prefab calibré créé/mis à jour :\n{prefabPath}\n\n" +
                "Utilisez ce Prefab dans vos futures scènes : son Scale affichera 1/1/1.",
                "OK");
        }

        static void FlipTriangles(Mesh mesh)
        {
            for (int sub = 0; sub < mesh.subMeshCount; sub++)
            {
                int[] triangles = mesh.GetTriangles(sub);
                for (int i = 0; i < triangles.Length; i += 3)
                {
                    int tmp = triangles[i];
                    triangles[i] = triangles[i + 1];
                    triangles[i + 1] = tmp;
                }
                mesh.SetTriangles(triangles, sub);
            }
        }

        static void EnsureFolderExists(string folder)
        {
            if (AssetDatabase.IsValidFolder(folder)) return;

            string[] parts = folder.Split('/');
            string current = parts[0];
            for (int i = 1; i < parts.Length; i++)
            {
                string next = current + "/" + parts[i];
                if (!AssetDatabase.IsValidFolder(next))
                    AssetDatabase.CreateFolder(current, parts[i]);
                current = next;
            }
        }

        static string SanitizeFileName(string name)
        {
            foreach (char c in Path.GetInvalidFileNameChars())
                name = name.Replace(c, '_');
            return name;
        }
        #endregion
    }
}